### PR TITLE
fix for read only assignment

### PR DESCRIPTION
**Pull request by shotlom**
**Fix for following error:**

genericComponent.js:129 Uncaught TypeError: Cannot assign to read only property 'tagName' of object '#<HTMLUListElement>'

### CODE REVIEW

**Comment by KoryNunn** [comment]
What case does this solve? Could you please provide a failing unit test for this change?

**Comment by shotlom** [comment]
genericComponent.js:129 Uncaught TypeError: Cannot assign to read only property 'tagName' of object '#<HTMLUListElement>'
    at Function.update [as _update] (genericComponent.js:129)
    at Object.updateProperty (property.js:122)
    at FastnComponent.onRender (baseComponent.js:27)
    at emitNone (events.js:101)
    at FastnComponent.emit (events.js:181)
    at FastnComponent.render (genericComponent.js:167)
    at insertChild (containerComponent.js:26)
    at Object.insert (containerComponent.js:56)
    at Object.insert (containerComponent.js:53)
    at emitNone (events.js:101)

**Comment by shotlom** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only

> What went wrong?
> The global variable or object property that was assigned to is a read-only property. (Technically, it is a non-writable data property.)
> 
> This error happens only in strict mode code. In non-strict code, the assignment is silently ignored.

**Comment by KoryNunn** [comment]
Can you past the code you have that causes this issue? Eg: `fastn('foo', ...)`

**Comment by shotlom** [comment]
```javaScript
var fastn = require('./setupFastn.js')

// Create a component to represent our app.
var todos = new fastn.Model({todos:[]});

function addTodo(todo){
    if(todo){
        todos.push('todos', todo);
    }
}

var newTodoBinding = fastn.binding('newTodo');

var app = fastn('div',
    fastn('list', {
        tagName: 'ul',
        items: fastn.binding('todos|*'),
        template: function(){
            return fastn('li', fastn.binding('item'));
        }
    }),
    fastn('form',
        fastn('input', {
            placeholder: 'New ToDo',
            value: newTodoBinding,
            onchange: 'value:value'
        }),
        fastn('button', 'Add #', fastn.binding('todos.length', function(length){
            return length + 1;
        }))
    ).on('submit', function(event){
        event.preventDefault();
        addTodo(newTodoBinding());
        todos.set('newTodo', '');
    })
)
.attach(todos).render();

document.body.appendChild(app.element);
```

**Comment by shotlom** [comment]
***./fastnSetup.js***

```javaScript
var fastn = require('./setupFastn.js')

// Create a component to represent our app.
var todos = new fastn.Model({todos:[]});

function addTodo(todo){
    if(todo){
        todos.push('todos', todo);
    }
}

var newTodoBinding = fastn.binding('newTodo');

var app = fastn('div',
    fastn('list', {
        tagName: 'ul',
        items: fastn.binding('todos|*'),
        template: function(){
            return fastn('li', fastn.binding('item'));
        }
    }),
    fastn('form',
        fastn('input', {
            placeholder: 'New ToDo',
            value: newTodoBinding,
            onchange: 'value:value'
        }),
        fastn('button', 'Add #', fastn.binding('todos.length', function(length){
            return length + 1;
        }))
    ).on('submit', function(event){
        event.preventDefault();
        addTodo(newTodoBinding());
        todos.set('newTodo', '');
    })
)
.attach(todos).render();

document.body.appendChild(app.element);

```

**Comment by shotlom** [comment]
Seems to be "strict mode" which makes a requirement for a "assign to read only property" unit test

**Comment by KoryNunn** [comment]
Hmm ok. I'll investigate.

**Comment by shotlom** [comment]
(I was testing bankai with fastn and just copied the fastn todos example)

**Comment by shotlom** [comment]
@KoryNunn,  what did your investigation find?

**Comment by KoryNunn** [comment]
I have implemented the todo example in a strict mode document and it works without issue: https://github.com/KoryNunn/fastn/blob/strict-test/test/strict.js

Maybe there is something wrong with the bundler you are trying to use?

**Comment by shotlom** [comment]
No I think it has to do with the assignment of a read only property 'tagName' of object '#'

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only

You could try to reproduce the problem by installing bankai and building that way. 

Alternately you could see whether the fix breaks anything in your applications, and if not then just implement it because it works for me with the fix.

**Comment by KoryNunn** [comment]
I don't have any runnable code that demonstraits that this is an issue with fastn. I am not going to implement changes in fastn that have no tests to validate the change. I have no idea what bankai is, nor do I intend to support it at this time. If you can provide a failing example I will investigate further. For now, I would suggest you don't build fastn applications with bankai.

**Comment by shotlom** [comment]
Hmmm, no I'm going the other way because bankai is just a wrapper around browserify and has some other very useful tools. So I'll stick with it. You should check it out.

Fastn has some nice features but this is a blocker to further usage.

**Comment by KoryNunn** [comment]
No problems, happy to re-open when I get some code that can reproduce this failure.

**Comment by shotlom** [comment]
Lols. Yeah, nah, it's not actually about you "getting some code".
The code required for the failure is given the above - a basic fastn example.
It's about you using bankai, and that is up to you.

**Pull request closed without merging**
